play_video:
  cron: "/15 * * * *"
  class: "PlayVideoJob" 
  queue: default
  
play_video2:
  cron: "/5 * * * *"
  class: "PlayVideoJob2" 
  queue: default

play_video3:
  cron: "/10 * * * *"
  class: "PlayVideoJob3" 
  queue: default  

play_video4:
  cron: "/12 * * * *"
  class: "PlayVideoJob4" 
  queue: default  